travis:
  secure:
    BINSTAR_TOKEN: dK4YH9BKx09I85lMA7wPypMGr8O9t+4hB7+oqjpBel4voNqqXE5QLqnGeXb8A3PCOhjubia3xzrHEjj5r6hnjWQHniRgCiOAp5j7kCiKir5nXveFTJYuyWpoMkOEWLaKqjvLF8XFYV8EvBhmK1YPiaNrIzSXnRSGM1BeGRPMaxwwDprdg1y1+X9ZLTKdWv4CureMAwmxXY5JOTw+nyRnCcqf4eJvv5aSFfk/7tHbQVaBQss5P8dgrkcQzRER46URtqBAfWkxIGr9WXTjsMgTguzed4VipdJyE0hNrETBcG4eQSDYjJuueujRYUIQyl50S7Ao4Rtemsz0o95ctsmJu7HypjaryN1gNxNEucpAdZYkpUyCFbrd1KLDq/qWBjgU7xnFyGKaPNdTDs0hXt3RCZoqx/JAij5t1i+OUan+pgjpO64MlD1K0wZCum3NjXF4xOKZwELPcJGUgDc96SJ+8YDAG9Rha7gsp6Kx3f+iDM5xHb2cPWxF9i7hbQDU9U1ieBM8wqo8HpUO8efwoYrqqOrtntMvKLqInmNLUZbruYajlOr3kU71+I59jD+FAFTObajGOhPSqHlQm0edm+/hQsqaLp0S3BPFoLrU0GkntcPpcCVKe1yIG6WHU+65ZLQ8xPb9PMohIHPemHymtHDuf4kQpijUmlH58gmImtZdUkI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
