travis:
  secure:
    BINSTAR_TOKEN: UyEEFt+ydeLJH87eklQDHtoAhQhkrmye/gk3RXOQe2LmXwQTHZO0PY37Wgg4IFqQIGiTk2eLJGjVnTX7J7YkWkXhD3olSGmr8CeGNEb6tSOF9DwCVST31ZKQMjJyh5jD+at+jSwJv+tIVpv9ak4U6fpLPTxNI4BRRxVCAE+SgLi/JjwvLIeN6SPWr7ny/ZZNsmheRSSTDPJmGsNmpqf8uVDgASF2oilqfd8Um5FQCkT1bDVyvDXycU3FCOoob33ayxRGzJAosQrSjNn5typ67F0cJkB4Fvx4UF5SkA+dbCVQq6YjYkkD9wFhHJGaE6f5oghiBB/hKEO+rowcgzfbAMgTXhI1vkctjZ7GVTtR2xCnPCxUYeSDHV09ptvIlMx9yugisGz1I/m9kIXA/vTDJMXXherPoR22ocoZ5E5I26zr2OHU/5QKqP2XTI043mPgmoq+on+lsDzzQGnLLwTRYMpBpcj71lhQJGgcJvC4hauUVaGfdhVuiQKBwoUVyaX2b0R6Sj9PnkpRhiiEv/F7C5T7NzxVAdKyDooLJwL+iirCTTIUk1VrASK0lbTD5GHVkOwhFRzNe2SeF/7m569ktU2z8n44YWsk3OpSrpsDrvpDluHmxPzJy2PzgS4ER257Wsk/7g9YovzgjQuToH1xEUAbki8ERaKhYnsi92ZwlIg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
