travis:
  secure:
    BINSTAR_TOKEN: ohr4djVcPMQA1fK3jrBtsYEMdPy82Box6zy4KszYewF85E8ku0l/VZ7QMa1PMyb+43ZhAn9IkBN5iAUYtoa+BAqOyMNOSgns7aYX/IEuBiEQqNo4nuwEEqrgOOtVaGMR36Fv2lNikZmKcTz6OKzBu4curt1Qxeh1kgLkPn2Vfdl8EzbkZ2Hb6V0MizqZ2NR0BA0rwiv6oL2rS9CHB/wvvHt5KfF/Utof8AxIIbQgvBX0t+Ky/vNsW8BAD/b17DVfeZoJr2gOIcw8CmtN7NO3pZTUZjdmH6Cpmbw8ToESdrm3kYF7URyfH6z9yuGl5U4+/Ve/acN7hDyzLey5EzOjIzJA0VBNebkhR4ssKXCreXivSJGbVulYrk9pJYWU5Gem+qA5SN+DiODCmEyaHW7B376LjjyIkVKiKkD05HRYLC7KTj6/GA4i/47JemccNBEpd6h/AjZ6mJ6iYbke03SQAapHuPfZbaoHjljpoXeqrhj5p9iK5/4QiO1kgeg2f/3DLkGwhBTM58/TNol9AWQwbAbNHCv7OtGqZghZPKZNT6r8h5M0PJYTBzxUetg6hjhiUda4JPXaDvVzlKeTFnGYHInrMPy/lsUtxwfXTfMAma44b3VM0ZR6yjm0v0Vpa/pyI9RF/PmoWMgaOjUnHfeyjHrrTvK/TzDPGBWZ4HQ4/rc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
